### PR TITLE
Uppercase titles derived from keys

### PR DESCRIPTION
**Pull request by tjconcept**

### CODE REVIEW

**Comment by citycide** [comment]
I usually like my header lower-cased but I'm probably the minority. How about making it an option like:

```js
tablemark([], { caseHeader: true })  // default
tablemark([], { caseHeader: false })  // old behavior
```

```js
return options.caseHeader
  ? key.slice(0, 1).toUpperCase() + key.slice(1)
  : key
```

**Comment by citycide** [comment]
@tjconcept I'm heading out on vacation for a week in a couple days, just wondering if we'd be able to finish this one up before then. No worries if not, but any thoughts on making this default but optional per my last comment?

**Comment by tjconcept** [comment]
Thoughts?

**Comment by tjconcept** [comment]
This works beautifully in combination with something like [flatson](https://www.npmjs.com/package/flatson) or [flat-stream](https://www.npmjs.com/package/flat-stream):

```sh
echo '{"error":{"code":1,"message":"Wrong"}}' | flat-stream | tablemark

| Error code | Error message |
| ---------- | ------------- |
| 1          | Wrong         |
```

**Comment by tjconcept** [comment]
FYI: if you like the other PR as well, don't bother the (tedious) merge. I have a branch and can easily rebase whichever way.

**Comment by citycide** [comment]
@tjconcept this looks good!

**Comment by tjconcept** [comment]
I'm wondering if the `caseHeader` should be `caseHeaders` (plural)?

Otherwise - ready for merge?

**Comment by citycide** [comment]
@tjconcept I had it in mind as `caseHeader{Row}`. If you think it needs to be more clear we should just go with that.

Otherwise this LGTM

**Pull request merged**
